rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - "RABBITMQ_DEFAULT_PASS=user"
    - "RABBITMQ_DEFAULT_USER=user"
    - "RABBITMQ_DEFAULT_VHOST='vhost'"
